/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import excepciones.ClienteDeudorException;
import excepciones.NoEncontradoException;
import excepciones.RutinaSinAvisoException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Otros.Gimnasio;
import model.ActivYrutina.*;
import model.Personal.Instructor;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author sergi
 */
public class DialogAgregarRutina extends javax.swing.JDialog {

    /**
     * Creates new form DialogAgregarComentario
     */
    private Gimnasio gimnasio;
    String dni_cliente_seleccionado;
    String json_cliente_seleccionado;
    public DialogAgregarRutina(java.awt.Frame parent, boolean modal,String dni_cliente_seleccionado,String json_cliente_seleccionado,Gimnasio gimnasio) {
        super(parent, modal);
        initComponents();
        this.gimnasio = gimnasio;
        btnAgregarRutina.putClientProperty( "JButton.buttonType", "roundRect" );
        this.dni_cliente_seleccionado = dni_cliente_seleccionado;
        this.json_cliente_seleccionado = json_cliente_seleccionado;
        

        InicializarComponentes();

    }
    private void InicializarComponentes(){
        //cargar text area
        CargarActividadesRealizadas();
        
        
        //cargar un combobox
        CargarNombresInstructores();
    }
    
    private void CargarNombresInstructores(){
        ArrayList <String> nombres_instructores =  ObtenerNombresInstructores();
        for(String nombre_instructor : nombres_instructores){
            cbNombresInstructores.addItem(nombre_instructor);
        }

    }
     private ArrayList<String> ObtenerNombresInstructores(){
        String json_instructores= gimnasio.CompartirDatosInstructores();
        ArrayList <String> nombres_instructores = new ArrayList<>();
        try {
            JSONArray jsonArray_clientes = new JSONArray(json_instructores);
            for(int i=0; i<jsonArray_clientes.length();i++){
                Instructor instructor = new Instructor();
                instructor = instructor.fromJson(jsonArray_clientes.getJSONObject(i));
                nombres_instructores.add(instructor.getNombre());
            }}catch(JSONException e){
                    Utilidades.MostrarMensajeInformativo(e.getMessage());
                    }
        return nombres_instructores;
        
    }

    private void CargarActividadesRealizadas(){
       String texto_actividades_realizadas = "Actividades Realizadas por Cliente:\n";
     
    try{
            JSONObject jSONObject_cliente = new JSONObject(json_cliente_seleccionado);
            JSONArray jSONArray_actividades = jSONObject_cliente.getJSONArray("Actividades");
            for(int i=0; i<jSONArray_actividades.length(); i++){
                JSONObject jSONObject_actividad = new JSONObject();
                jSONObject_actividad = jSONArray_actividades.getJSONObject(i);
                
                Actividad actividad = new Actividad();
                actividad = actividad.fromJson(jSONObject_actividad);
                texto_actividades_realizadas += actividad.getNombre().name() + "\n";
                
                
            }
            taActividadesRealizadas.setText(texto_actividades_realizadas);
        }catch(JSONException e){
            Utilidades.MostrarMensajeWarning("Hubo un problema al recuperar datos del cliente");
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        cbNombresInstructores = new javax.swing.JComboBox<>();
        btnAgregarRutina = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taActividadesRealizadas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfDescripcionRutina = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar");
        setResizable(false);

        btnAgregarRutina.setText("Agregar");
        btnAgregarRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRutinaActionPerformed(evt);
            }
        });

        taActividadesRealizadas.setEditable(false);
        taActividadesRealizadas.setColumns(20);
        taActividadesRealizadas.setRows(5);
        jScrollPane1.setViewportView(taActividadesRealizadas);

        tfDescripcionRutina.setColumns(20);
        tfDescripcionRutina.setRows(5);
        tfDescripcionRutina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescripcionRutinaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tfDescripcionRutina);

        jLabel1.setText("Instructor");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnAgregarRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNombresInstructores, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNombresInstructores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAgregarRutina)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRutinaActionPerformed
        // TODO add your handling code here:
        AgregarRutina();

    }//GEN-LAST:event_btnAgregarRutinaActionPerformed

    private void tfDescripcionRutinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionRutinaKeyPressed
        // TODO add your handling code here:
              if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfDescripcionRutina.append("\n"); // Insertar salto de línea al presionar Enter
        }
    }//GEN-LAST:event_tfDescripcionRutinaKeyPressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAgregarRutina;
    private javax.swing.JComboBox<String> cbNombresInstructores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taActividadesRealizadas;
    private javax.swing.JTextArea tfDescripcionRutina;
    // End of variables declaration//GEN-END:variables

    private void AgregarRutina() {
        
         //"La rutina agregada reemplazará la anterior. Confirme operación"
        // Confirmar  - Cancelar
        
                String []opciones = {"Cancelar", "Confirmar"};
        int rta = JOptionPane.showOptionDialog(null,"La rutina agregada reemplazará la anterior. Confirme operación", "Atención", 
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, 
                null, opciones, opciones[1]);
        
        if(rta==1){
                   try{
            gimnasio.agregarRutina(dni_cliente_seleccionado,(String)cbNombresInstructores.getSelectedItem(),tfDescripcionRutina.getText());
            this.dispose(); //cerrar ventana
        }catch(NoEncontradoException e){
            Utilidades.MostrarMensajeWarning(e.getMessage());
        }catch(ClienteDeudorException e){
            Utilidades.MostrarMensajeWarning("El cliente presenta deuda. No es posible agregar rutina");
        }
            
        }
    

       
        

        
        
    }


}
