/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;
import static UI.Utilidades.MostrarMensajeInformativo;
import excepciones.ExistenteException;
import excepciones.UsuarioExistenteException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Enum.EGenero;
import model.Enum.EGrupoSanguineo;
import model.Otros.Gimnasio;
import model.Personal.Administrativo;
import model.Personal.Usuario;


/**
 *
 * @author sergi
 */
public class DialogRegistrarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form DialogRegistrarUsuario
     */
    private Gimnasio gimnasio;
    public DialogRegistrarUsuario(java.awt.Frame parent, boolean modal,Gimnasio gimnasio) {
        super(parent, modal);
        this.gimnasio = gimnasio;
        initComponents();
        CargarComponentes();
        

    }
     private void CargarComponentes(){
        CargarComboBox();
        btnConfirmar.putClientProperty( "JButton.buttonType", "roundRect" ); //botoncircular
        cbGenero.setSelectedIndex(-1);
        cbGrupoSanguineo.setSelectedIndex(-1);
    }
    private void CargarComboBox(){
        for (EGrupoSanguineo grupo_sanguineo : EGrupoSanguineo.values()) {
            cbGrupoSanguineo.addItem(grupo_sanguineo.name());
        }
        
                for (EGenero genero : EGenero.values()) {
            cbGenero.addItem(genero.name());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuil = new javax.swing.JLabel();
        tfCuil = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        tfTelEmergencia = new javax.swing.JTextField();
        lblTelEmergencia = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        lblObraSocial = new javax.swing.JLabel();
        tfObraSocial = new javax.swing.JTextField();
        lblGrupoSanguineo = new javax.swing.JLabel();
        cbGrupoSanguineo = new javax.swing.JComboBox<>();
        lblDni1 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        lblDni2 = new javax.swing.JLabel();
        lblDni3 = new javax.swing.JLabel();
        tfNombreDeUsuario = new javax.swing.JTextField();
        lblDni4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        tfDomicilio = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        lblTelEmergencia1 = new javax.swing.JLabel();
        pfRepetirContrasenia = new javax.swing.JPasswordField();
        pfContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCuil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCuil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCuil.setText("CUIL");

        tfCuil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCuilKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Género");

        lblDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDomicilio.setText("Domicilio");

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyTyped(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Teléfono");

        tfTelEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTelEmergencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelEmergenciaKeyTyped(evt);
            }
        });

        lblTelEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelEmergencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelEmergencia.setText("Tel. Emergencia");
        lblTelEmergencia.setToolTipText("");

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaNacimiento.setText("Fecha de Nacimiento");
        lblFechaNacimiento.setToolTipText("");

        dcFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblObraSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObraSocial.setText("Obra Social");
        lblObraSocial.setToolTipText("");

        tfObraSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGrupoSanguineo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrupoSanguineo.setText("Grupo Sanguíneo");
        lblGrupoSanguineo.setToolTipText("");

        cbGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDni1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni1.setText("DNI");

        tfDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDniKeyTyped(evt);
            }
        });

        lblDni2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDni2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni2.setText("Contraseña");

        lblDni3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDni3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni3.setText("Nombre de Usuario");

        tfNombreDeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDni4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDni4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni4.setText("Repetir Contraseña");

        btnConfirmar.setText("Agregar Usuario");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre1.setText("Nombre");

        tfDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTelEmergencia1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelEmergencia1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelEmergencia1.setText("Email");
        lblTelEmergencia1.setToolTipText("");

        pfRepetirContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pfContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaNacimiento)
                                    .addComponent(lblTelEmergencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblDni3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(lblDni2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(lblDni4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfRepetirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuil)
                    .addComponent(tfCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilio)
                    .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelEmergencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelEmergencia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNacimiento)
                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObraSocial)
                    .addComponent(tfObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupoSanguineo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni3))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni2)
                    .addComponent(pfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni4)
                    .addComponent(pfRepetirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        if(ContraseniasCoinciden() && ValidarCamposCompletos()){
              AgregarUsuario();
        }else{
            Utilidades.MostrarMensajeWarning("Las contraseñas no coinciden!");
        }

        /*     Date fecha_date = dcFechaNacimiento.getDate();
        Instant instant = fecha_date.toInstant();
        ZoneId zoneId = ZoneId.systemDefault();
        LocalDate local_date_usuario = instant.atZone(zoneId).toLocalDate();
        */
        //enum
        ////   String enum_elegido = (String)cbGrupoSanguineo.getSelectedItem();
        //  EGrupoSanguineo enum_autentico = EGrupoSanguineo.valueOf(enum_elegido);
        //EGrupoSanguineo enum_elegido = (EGrupoSanguineo) cbGrupoSanguineo.getSelectedItem();

        //  Utilidades.MostrarMensajeInformativo("Seleccionaste el dia: " + local_date_usuario.toString() + " y tu grupo sanguineo es " + enum_elegido + " y el enum autentico es " + enum_autentico.name());
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void tfDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();

    }//GEN-LAST:event_tfDniKeyTyped

    private void tfCuilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCuilKeyTyped
        // TODO add your handling code here:
        //Solo numeros y guion
   char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || c == '-')) {
        evt.consume(); 
    }

    }//GEN-LAST:event_tfCuilKeyTyped

    private void tfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyTyped
        // TODO add your handling code here:
        //Solo numeros - parentesis y guion
    char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || c == '(' || c == ')' || c == '-')) {
        evt.consume(); 
    }

    }//GEN-LAST:event_tfTelefonoKeyTyped

    private void tfTelEmergenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelEmergenciaKeyTyped
        // TODO add your handling code here:
        //Solo numeros - parentesis y guion
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '(' || c == ')' || c == '-')) {
            evt.consume(); 
        }

    }//GEN-LAST:event_tfTelEmergenciaKeyTyped

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbGrupoSanguineo;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCuil;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblDni2;
    private javax.swing.JLabel lblDni3;
    private javax.swing.JLabel lblDni4;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGrupoSanguineo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblObraSocial;
    private javax.swing.JLabel lblTelEmergencia;
    private javax.swing.JLabel lblTelEmergencia1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPasswordField pfContrasenia;
    private javax.swing.JPasswordField pfRepetirContrasenia;
    private javax.swing.JTextField tfCuil;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfDomicilio;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreDeUsuario;
    private javax.swing.JTextField tfObraSocial;
    private javax.swing.JTextField tfTelEmergencia;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables

    private void AgregarUsuario() {
        //metodo que es llamado al pulsar el boton de confirmar , se sirve del back
        //Fecha de Nacimiento
        Date fecha_date = dcFechaNacimiento.getDate();
        Instant instant = fecha_date.toInstant();
        ZoneId zoneId = ZoneId.systemDefault();
        LocalDate fecha_de_nacimiento = instant.atZone(zoneId).toLocalDate();

        //Grupo Sanguineo
        String enum_formato_string = (String) cbGrupoSanguineo.getSelectedItem();
        EGrupoSanguineo grupo_sanguineo = EGrupoSanguineo.valueOf(enum_formato_string);

        //Genero
        String genero_formato_string = (String) cbGenero.getSelectedItem();
        EGenero genero = EGenero.valueOf(genero_formato_string);

        Usuario usuario = new Administrativo(tfNombre.getText(), tfDni.getText(), genero, tfTelefono.getText(),
                tfDomicilio.getText(), tfEmail.getText(), grupo_sanguineo, tfTelEmergencia.getText(),
                tfObraSocial.getText(), fecha_de_nacimiento, "", tfCuil.getText(), tfNombreDeUsuario.getText(), String.valueOf(pfContrasenia.getPassword()));

        try {
            gimnasio.agregar(usuario);
            Utilidades.MostrarMensajeInformativo("El usuario fue agregado exitosamente");
            this.dispose();

        } catch (ExistenteException e) {
            Utilidades.MostrarMensajeWarning("El nombre de usuario elegido no está disponible");
        }

    }
        private boolean ContraseniasCoinciden() {
        //metodo que verifica que coincidan las contrasenias
        boolean rta = false;
        if(String.valueOf(pfContrasenia.getPassword()).equals(String.valueOf(pfRepetirContrasenia.getPassword()))){
            rta = true;
        }
        return rta;
    }

    private boolean ValidarCamposCompletos() {
        boolean rta = false;
        if (CampoInvalido(tfDni.getText()) || CampoInvalido(tfNombre.getText()) || CampoInvalido(tfCuil.getText()) || CampoInvalido(tfDomicilio.getText()) || CampoInvalido(tfTelefono.getText()) || CampoInvalido(tfTelEmergencia.getText())
                || CampoInvalido(tfEmail.getText()) || CampoInvalido(tfObraSocial.getText()) || cbGenero.getSelectedIndex() < 0 || cbGrupoSanguineo.getSelectedIndex() < 0 || dcFechaNacimiento.getDate() == null) {
            Utilidades.MostrarMensajeWarning("Todos los campos deben estar completos!");
        } else {
            rta = true;
        }
        return rta;
        
    }
    
    private boolean CampoInvalido(String texto){
       boolean rta = false;
        if (texto == null || texto.trim().isEmpty()) {
            rta = true;
        } 
        return rta;
    }
}
