/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import excepciones.ExistenteException;
import excepciones.NoEncontradoException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import model.Enum.EGenero;
import model.Enum.EGrupoSanguineo;
import model.Enum.Eestado;
import model.Otros.Gimnasio;
import model.Personal.Instructor;
import model.Personal.Usuario;

/**
 *
 * @author sergi
 */
public class DialogModificarInstructor extends javax.swing.JDialog {

    /**
     * Creates new form DialogAgregarInstructor
     */
    private Gimnasio gimnasio;
    private Instructor instructor_a_modificar;
    public DialogModificarInstructor(java.awt.Frame parent, boolean modal,Gimnasio gimnasio,Instructor instructor_a_modificar) {
        super(parent, modal);
        initComponents();
        
        this.gimnasio = gimnasio;
        this.instructor_a_modificar = instructor_a_modificar;
        CargarComponentes();
        SetearCampos();

    }
    
    private void CargarComponentes(){
        CargarComboBox();
        btnConfirmar.putClientProperty( "JButton.buttonType", "roundRect" ); //botoncircular
    }
    private void CargarComboBox(){
        for (EGrupoSanguineo grupo_sanguineo : EGrupoSanguineo.values()) {
            cbGrupoSanguineo.addItem(grupo_sanguineo.name());
        }
        
                for (EGenero genero : EGenero.values()) {
            cbGenero.addItem(genero.name());
        }
    }
    
    private void SetearCampos(){
        //metodo para mostrar campos modificables en pantalla
        tfDni.setText(instructor_a_modificar.getDni());//inmodificable
        tfNombre.setText(instructor_a_modificar.getNombre());
        
        cbGenero.setSelectedItem(instructor_a_modificar.getGenero());
        
        tfDomicilio.setText(instructor_a_modificar.getDomicilio());
        
        //pasamos de localdate a date?
        LocalDate localdate_fecha_nacimiento = instructor_a_modificar.getFecha_nacimiento();
        ZoneId zoneId = ZoneId.systemDefault();
        Date date_fecha_nacimiento = Date.from(localdate_fecha_nacimiento.atStartOfDay(zoneId).toInstant());
        dcFechaNacimiento.setDate(date_fecha_nacimiento);
        
        tfTelefono.setText(instructor_a_modificar.getTelefono());
        tfTelEmergencia.setText(instructor_a_modificar.getContacto_emergencia());
        tfEmail.setText(instructor_a_modificar.getEmail());
        tfObraSocial.setText(instructor_a_modificar.getObra_social());
        
        cbGrupoSanguineo.setSelectedItem(instructor_a_modificar.getGrupo_sanguineo());
        
        tfCuil.setText(instructor_a_modificar.getCUIL());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuil = new javax.swing.JLabel();
        tfCuil = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        tfTelEmergencia = new javax.swing.JTextField();
        lblTelEmergencia = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        lblObraSocial = new javax.swing.JLabel();
        tfObraSocial = new javax.swing.JTextField();
        lblGrupoSanguineo = new javax.swing.JLabel();
        cbGrupoSanguineo = new javax.swing.JComboBox<>();
        lblDni1 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        tfDomicilio = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        lblTelEmergencia1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCuil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCuil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCuil.setText("CUIL");

        tfCuil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCuilKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Género");

        lblDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDomicilio.setText("Domicilio");

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyTyped(evt);
            }
        });

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Teléfono");

        tfTelEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTelEmergencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelEmergenciaKeyTyped(evt);
            }
        });

        lblTelEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelEmergencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelEmergencia.setText("Tel. Emergencia");
        lblTelEmergencia.setToolTipText("");

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaNacimiento.setText("Fecha de Nacimiento");
        lblFechaNacimiento.setToolTipText("");

        dcFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblObraSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObraSocial.setText("Obra Social");
        lblObraSocial.setToolTipText("");

        tfObraSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGrupoSanguineo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrupoSanguineo.setText("Grupo Sanguíneo");
        lblGrupoSanguineo.setToolTipText("");

        cbGrupoSanguineo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDni1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni1.setText("DNI");

        tfDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfDni.setEnabled(false);

        btnConfirmar.setText("Modificar ");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre1.setText("Nombre");

        tfDomicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTelEmergencia1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelEmergencia1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelEmergencia1.setText("Email");
        lblTelEmergencia1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaNacimiento)
                                    .addComponent(lblTelEmergencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuil)
                    .addComponent(tfCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilio)
                    .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelEmergencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelEmergencia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNacimiento)
                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObraSocial)
                    .addComponent(tfObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupoSanguineo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        if(ValidarCamposCompletos()){
              ModificarInstructor();
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void tfCuilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCuilKeyTyped
        // TODO add your handling code here:
        //Solo numeros y guion
   char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || c == '-')) {
        evt.consume(); 
    }

    }//GEN-LAST:event_tfCuilKeyTyped

    private void tfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyTyped
        // TODO add your handling code here:
        //Solo numeros - parentesis y guion - telefonos
    char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || c == '(' || c == ')' || c == '-')) {
        evt.consume(); 
    }

    }//GEN-LAST:event_tfTelefonoKeyTyped

    private void tfTelEmergenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelEmergenciaKeyTyped
        // TODO add your handling code here:
        //Solo numeros - parentesis y guion - telefonos
    char c = evt.getKeyChar();
    if (!(Character.isDigit(c) || c == '(' || c == ')' || c == '-')) {
        evt.consume(); 
    }

    }//GEN-LAST:event_tfTelEmergenciaKeyTyped

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbGrupoSanguineo;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuil;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGrupoSanguineo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblObraSocial;
    private javax.swing.JLabel lblTelEmergencia;
    private javax.swing.JLabel lblTelEmergencia1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField tfCuil;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfDomicilio;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfObraSocial;
    private javax.swing.JTextField tfTelEmergencia;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables



    private void ModificarInstructor() {
        //metodo invocado al pulsar boton de modificar (instructor)
        //Fecha de Nacimiento
        Date fecha_date = dcFechaNacimiento.getDate();
        Instant instant = fecha_date.toInstant();
        ZoneId zoneId = ZoneId.systemDefault();
        LocalDate fecha_de_nacimiento = instant.atZone(zoneId).toLocalDate();

        //Grupo Sanguineo
        String enum_formato_string = (String) cbGrupoSanguineo.getSelectedItem();
        EGrupoSanguineo grupo_sanguineo = EGrupoSanguineo.valueOf(enum_formato_string);

        //Genero
        String genero_formato_string = (String) cbGenero.getSelectedItem();
        EGenero genero = EGenero.valueOf(genero_formato_string);

        try {

            gimnasio.modificarInstructor(tfDni.getText(), tfNombre.getText(), tfDni.getText(), genero,
                    tfTelefono.getText(), tfDomicilio.getText(), tfEmail.getText(), instructor_a_modificar.getEstado(), grupo_sanguineo,
                    tfTelEmergencia.getText(), tfObraSocial.getText(), fecha_de_nacimiento, instructor_a_modificar.getComentario(),
                    tfCuil.getText(), instructor_a_modificar.getImagenPerfil());
            Utilidades.MostrarMensajeInformativo("El instructor ha sido modificado exitosamente!");
            this.dispose();

        } catch (NoEncontradoException e) {
            Utilidades.MostrarMensajeWarning(e.getMessage());
        }
        
    }
    private boolean ValidarCamposCompletos() {
        boolean rta = false;
        if(CampoInvalido(tfDni.getText()) || CampoInvalido(tfNombre.getText()) || CampoInvalido(tfCuil.getText()) || CampoInvalido(tfDomicilio.getText()) || CampoInvalido(tfTelefono.getText()) || CampoInvalido(tfTelEmergencia.getText())
                || CampoInvalido(tfEmail.getText()) || CampoInvalido(tfObraSocial.getText()) || cbGenero.getSelectedIndex()<0 || cbGrupoSanguineo.getSelectedIndex()<0 || dcFechaNacimiento.getDate()==null){
            Utilidades.MostrarMensajeWarning("Todos los campos deben estar completos!");
        }else{
            rta = true;
        }
        return rta;
        
    }
    
    private boolean CampoInvalido(String texto){
       boolean rta = false;
        if (texto == null || texto.trim().isEmpty()) {
            rta = true;
        } 
        return rta;
    }
}
